import { useEffect, useRef, useState } from 'react';
import { MessageCircle, X, Send } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

interface Props {
  lang?: 'en' | 'ko';
}

export default function AskWidget({ lang: initialLang }: Props) {
  const [lang, setLang] = useState<'en' | 'ko'>(initialLang ?? 'en');
  const [open, setOpen] = useState(false);
  const [q, setQ] = useState('');
  const [a, setA] = useState('');
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [remaining, setRemaining] = useState<number | null>(null);
  const aborter = useRef<AbortController | null>(null);

  useEffect(() => {
    const docLang = document.documentElement.lang;
    if (docLang === 'ko' || docLang === 'en') setLang(docLang);
    const opener = () => setOpen(true);
    window.addEventListener('personal-site:open-ask', opener);
    return () => window.removeEventListener('personal-site:open-ask', opener);
  }, []);

  async function submit() {
    if (!q.trim() || busy) return;
    setBusy(true);
    setA('');
    setErr(null);
    aborter.current?.abort();
    const ac = new AbortController();
    aborter.current = ac;
    try {
      const resp = await fetch('/api/ask', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ question: q, lang }),
        signal: ac.signal,
      });
      if (!resp.ok) {
        const j = await resp.json().catch(() => ({ error: resp.statusText }));
        setErr(j.error || 'Error');
        setBusy(false);
        return;
      }
      const remHeader = resp.headers.get('x-ratelimit-remaining');
      if (remHeader) setRemaining(parseInt(remHeader, 10));

      const reader = resp.body!.getReader();
      const decoder = new TextDecoder();
      let buffer = '';
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        let nl;
        while ((nl = buffer.indexOf('\n\n')) !== -1) {
          const event = buffer.slice(0, nl);
          buffer = buffer.slice(nl + 2);
          for (const line of event.split('\n')) {
            if (line.startsWith('data: ')) {
              try {
                const data = JSON.parse(line.slice(6));
                if (data.type === 'content_block_delta' && data.delta?.type === 'text_delta') {
                  setA((prev) => prev + data.delta.text);
                }
              } catch {
                /* ignore non-JSON SSE frames */
              }
            }
          }
        }
      }
    } catch (e: any) {
      if (e.name !== 'AbortError') setErr(String(e.message ?? e));
    } finally {
      setBusy(false);
    }
  }

  const placeholder =
    lang === 'ko' ? '예: KURO의 핵심 알고리즘은 무엇인가요?' : 'e.g., What is the core algorithm of KURO?';
  const disclaimer =
    lang === 'ko' ? 'Claude 생성 답변. 정확성은 원문 참고.' : 'Answers generated by Claude — verify against papers.';

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        aria-label={lang === 'ko' ? 'AI에게 질문하기' : 'Ask AI about Gyumin'}
        className="fixed bottom-6 right-6 z-50 size-14 rounded-full bg-primary text-primary-foreground shadow-lg hover:shadow-xl flex items-center justify-center transition-shadow"
      >
        <MessageCircle className="size-6" />
      </button>

      {open && (
        <div
          className="fixed inset-0 z-50 bg-background/80 backdrop-blur-md flex items-end md:items-center justify-center md:p-4"
          onClick={(e) => {
            if (e.target === e.currentTarget) setOpen(false);
          }}
        >
          <div className="w-full max-w-xl bg-card border border-border rounded-t-lg md:rounded-lg shadow-lg overflow-hidden flex flex-col max-h-[85vh]">
            <header className="flex items-center justify-between px-4 py-3 border-b border-border">
              <h2 className="text-sm font-semibold">
                {lang === 'ko' ? '이규민에 대해 질문하기' : 'Ask AI about Gyumin'}
              </h2>
              <button
                type="button"
                onClick={() => setOpen(false)}
                aria-label="Close"
                className="p-1 rounded hover:bg-muted"
              >
                <X className="size-4" />
              </button>
            </header>

            <div className="p-4 flex-1 overflow-y-auto">
              {a && (
                <div className="prose prose-sm max-w-none text-foreground">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>{a + (busy ? '▍' : '')}</ReactMarkdown>
                </div>
              )}
              {err && <p className="text-sm text-destructive">{err}</p>}
              {!a && !err && !busy && <p className="text-sm text-muted-foreground">{placeholder}</p>}
            </div>

            <footer className="border-t border-border p-3">
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  submit();
                }}
                className="flex items-end gap-2"
              >
                <textarea
                  id="ask-question"
                  name="ask-question"
                  aria-label={lang === 'ko' ? '이규민에 대해 질문' : 'Ask a question about Gyumin'}
                  value={q}
                  onChange={(e) => setQ(e.target.value)}
                  rows={1}
                  placeholder={placeholder}
                  className="flex-1 resize-none bg-background border border-border rounded-md px-3 py-2 text-sm outline-none focus:border-primary"
                  maxLength={500}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) submit();
                  }}
                />
                <button
                  type="submit"
                  disabled={busy || !q.trim()}
                  aria-label="Send"
                  className="size-9 rounded-md bg-primary text-primary-foreground flex items-center justify-center disabled:opacity-40"
                >
                  <Send className="size-4" />
                </button>
              </form>
              <p className="text-xs text-muted-foreground mt-2 flex justify-between">
                <span>{disclaimer}</span>
                {remaining !== null && (
                  <span>{lang === 'ko' ? `남은 질문 ${remaining}/10` : `${remaining}/10 left`}</span>
                )}
              </p>
            </footer>
          </div>
        </div>
      )}
    </>
  );
}
